version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - dbsql
      - redis_cache
  dbsql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

  redis_cache:
    image: redis:7.2
    container_name: redis_docker
    ports:
      - '6379:6379'

volumes:
  db_data:
